export const SITE = {
  website: "https://austinsmith.org",
  author: "Austin Smith",
  profile: "https://github.com/austindsmith",
  desc: "My website",
  title: "Austin Smith",
  ogImage: "devosfera-og.webp",
  lightAndDarkMode: true,
  postPerIndex: 6,
  postPerPage: 8,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showGalleries: true,
  showBackButton: true,
  editPost: {
    enabled: true,
    text: "Edit this post",
    url: "https://github.com/austindsmith/austin-smith/edit/main/",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "en",
  timezone: "America/Denver",
  introAudio: {
    enabled: true,
    src: "/audio/intro-web.mp3",
    label: "INTRO.MP3",
    duration: 30,
  },
} as const;
